### ISSUE TITLE
Questions about Secondary PM2.5 Increments and PM2.5 Model Inputs

### ISSUE THREAD

**Issue by stwcn1** [epri-dev/SCICHEM#10]
Hello, I have some questions about how to input PM2.5 into SCICHEM and about secondary PM2.5 using SCIDOSPOST. I would appreciate your help.

1.Does the secondary PM2.5 extracted by the SCIDOSPOST module consider the effects of sulfates and nitrates like CALPUFF does?

2. How to specify the emission rate of PM2.5?
       In my .inp file, I have specified a particulate material named PM, with bin boundaries from 1 to 10 microns, as shown in figs. How do I specify the emission rate of PM2.5 in the .scn file?   If the material is gaseous, you can add various gaseous pollutant emission rates under the #START_MC line. However, **if the material is particulate, adding the emission rate of PM2.5 under the #START_MC line does not affect the simulation results. So I am confused about where to specify the emission rate of PM2.5**. Could you provide an example of the **.inp and .scn files?** I would greatly appreciate it.
![image](https://github.com/user-attachments/assets/44c9c30e-2f83-47cb-bfe2-15116793e19b)
![image](https://github.com/user-attachments/assets/82cdd3fd-e1c8-466e-9102-c8057ccbb3f5)

**Comment by pkaramchandani** [comment]
Hi

As Doug mentioned, when you do a chemistry run, PM25 is a group of components that is used only for the post-processing. You should specify emission rates for one or more of those components (if you don't know the composition of the PM2.5 and you want to treat it as just inert PM you can specify emissions for A25J)
