### ISSUE TITLE
Questions about the output of single source contributions

### ISSUE THREAD

**Issue by stwcn1** [epri-dev/SCICHEM#11]
Hello, I have input multiple sources into the SCN file. Is it possible to output the contribution concentration of each source to the receptors or grids?  Could you please provide guidance on how to achieve this? Your assistance would be greatly appreciated.Thank you very much.

**Comment by DougHenn1** [comment]
The only way to do that is to define separate materials for each source (and additional receptors) or run separate calculations for each source.

**Comment by stwcn1** [comment]
Thank you for your reply. After defining a separate material for each source, how can I output the concentration of that source at the receptors or grid cells? Is it possible to achieve this using sciDospost?

**Comment by DougHenn1** [comment]
You should be able to use SciDosPost assuming all "GROUP_DOSE" = T for all materials in the .inp file (or GASDEPOS is specified in the .sci file).  Of course, that will give you time-averaged concentration.

If you're specifying receptors, you need to define multiple receptors at each location.  I don't know how you're defining the materials, but assuming you've defined materials TRAC1, TRAC2, ... for the multiple releases, and you're looking at component SO2 (as in the so2_2005 example case), the receptor file (SMPFILE in the .inp file or RE SAMPFILE FILENAME in the .sci file) might look like

SCIPUFF SENSOR
500   4000  0.  MC TRAC1:(SO2)
500   4000  0.  MC TRAC2(SO2)
...
510   4000  0.  MC TRAC1:(SO2)
510   4000  0.  MC TRAC1(SO2)
...

**Comment by stwcn1** [comment]
Thank you for your reply. I understand what you're saying about how to obtain the contribution concentration from each source to a receptor. However, as you know, if I want to obtain the contribution concentration from each source to a new receptor, I have to rerun the simulation. So, I'd like to ask if it's possible to use SciDosPost to calculate the contribution concentration from each source to a receptor. It seems that using SciDosPost only provides the sum of the contribution concentrations from all sources to the receptor, rather than the contribution concentration from each source to the receptor.

**Comment by DougHenn1** [comment]
I was suggesting multiple tracer materials corresponding to the sources, so their contributions would not be be summed.  However, I don't know how/if that would be handled in SciDosPost. (I'm not the author.)  A possible alternative is to define multiple components in the IMC file and only release those from the corresponding sources.

I will bring in the SciDosPost expert to this thread.

**Comment by pkaramchandani** [comment]
Hi

SCICHEM does not have source apportionment capability at this point. sciDOSpost does not have the capability to distinguish source types from the SCICHEM outputs for a single run with the same tracer material and same species names. Doug's suggestions above are the only way to get the results you are looking for.

**Comment by stwcn1** [comment]
Thank you for your reply.
