### ISSUE TITLE
Questions about optimizing Meteorological Data Selection and Integration in Air Quality Modeling

### ISSUE THREAD

**Issue by stwcn1** [epri-dev/SCICHEM#15]
Hello, I'd like to ask you a few questions about the SCICHEM model's meteorological data input.Could you please provide some assistance. Thank you very much.
1.If meteorological data is input using the SCIPUFF_LIST format with both AERSFC and MCW data, will the model adjust the wind field and other meteorological variables in the grid meteorology based on the data from AERSFC?
2.If all meteorological data are available, which type of meteorological data do you recommend most?

**Comment by DougHenn1** [comment]
1. If the AERSFC  file (or other types of observational input) is listed after the MCW file, SCICHEM will assimilate the winds and other 3d data (if given, but not 2d fields like boundary layer depth) into the 3d MCW fields.  However, this is not really a "published" feature. For example, it is not discussed in the SCICHEM technical document but there are relevant parameters that can be set in the list file (shown with the default values):
R_OBS          10000.0     !Observation radius of influence (meters)
E2BO           9.0             !Ratio of background error variance to observation error variance
ASSIM_MAXITER  10       !Maximum number of  iterations for assimilation procedure
MC_OBSWTFAC    0   !Factor for observation weights in mass-consistent flow field adjustment (but 4 is now recommended)
ASSIM_EPS      0.001     !Assimilation convergence criterion
 
Bottom line:  this is really a "beta" feature that has not been extensively tested.  You're welcome to try it - I think you'd probably be the first SCICHEM user to do so.

2. The "best" data depends on your application and the data.  For short range, I would recommend observations if they're close to the source (within a few kilometers), especially if you're doing a short-range calculation (out to 10km, say).  However, if the observations are more than a few kilometers away or if you're doing a long-range calculation, I recommended gridded data, which presumably has assimilated observations into a good NWP model like WRF.  Obviously, assimilating observations into a gridded field, as discussed above, blends these approaches so it could be ideal - except that it is largely untested in SCICHEM.
