### ISSUE TITLE
question

### ISSUE THREAD

**Issue by qingfengnanmeng** [epri-dev/SCICHEM#3]
Hello, after running SCIPUFF to successfully generate dos, ados, dep files, when running sciDosPost.exe, sciDosPost.exe appears to be flashing, what is the reason for this?
<img width="583" alt="6a74a019aeed80037c508595011acea" src="https://user-images.githubusercontent.com/127366298/223899243-2503b50b-45b6-4dd9-bf22-946182f86e3d.png">

**Comment by DougHenn** [comment]
The error occurred when sciDOSpost attempted to write to the file scipuff.ini.  Since you got to this point, I believe sciDOSpost has verified that the file exists, so I'm not sure what the problem is.  Could another application be accessing scipuff.ini at the same time? I assume you're using run_scidospost.bat. Make sure the paths are appropriately set up for you.

**Comment by qingfengnanmeng** [comment]
> The error occurred when sciDOSpost attempted to write to the file scipuff.ini. Since you got to this point, I believe sciDOSpost has verified that the file exists, so I'm not sure what the problem is. Could another application be accessing scipuff.ini at the same time? I assume you're using run_scidospost.bat. Make sure the paths are appropriately set up for you.
Thank you very much for your answer. After I set the path in run_sciDOSpost.bat, the problem has been solved. But when creating the receptor location, an error occurred. I don't understand the error. Is it because the "band" cannot be found in the flag.2010.table.6.annual.csv? But "band" row actually exists. At the same time, I also want to ask how to plot according to the model results in the Linux system,I would be grateful if you can give any assistance.
![image](https://user-images.githubusercontent.com/127366298/224257278-0ae13f23-cbea-4877-8d16-3bc6c1035494.png)

![image](https://user-images.githubusercontent.com/127366298/224257356-d5da6482-9f61-4b03-a258-100482dde369.png)

**Comment by qingfengnanmeng** [comment]
Thank you very much for your answer. After I set the path in run_sciDOSpost.bat, the problem has been solved. But when creating the receptor location, an error occurred. I don't understand the error. Is it because the "band" cannot be found in the flag.2010.table.6.annual.csv? But "band" row actually exists. At the same time, I also want to ask how to plot according to the model results in the Linux system,I would be grateful if you can give any assistance.
![8a85f5dd6851ebb6bcb3c924ab4a6a7](https://user-images.githubusercontent.com/127366298/224266591-7f7bfe80-b5d1-4b4e-a0f6-5c9a5e840732.png)
![283ea53e301973cffe9adb3fcab85c9](https://user-images.githubusercontent.com/127366298/224266610-2c6b901d-13e9-40f8-9fcc-6fe21ef1b7f3.png)

**Comment by DougHenn** [comment]
There is a coding issue in SCIDOSPOST where it converts to upper case names when searching for receptor names.  A workaround is to give the receptor names in upper in the SCIDOSPOST input file.  An example is attached.
[SW_SS.sciDOSpost_UC.log](https://github.com/epri-dev/SCICHEM/files/10961949/SW_SS.sciDOSpost_UC.log)

However, I eventually get a different error.  But note that I tested this with a shortened SCICHEM calculation, and it is possible that the SCIDOSPOST calculation could work with 16 days of data.  Please let me know if it works for you.

**Comment by qingfengnanmeng** [comment]
I tried SCIDOSPOST running with 16 days of data but it didn't work, changing the receptor name to SW_ss also didn't work.
1. Is there a problem in initializing the visibility?
2. I can't find the NatCond file, do I need to create this file myself?

Here is the inp file I entered（The contents of the SW_SS.sciDOSpost.inp  are copied to the txt for easy upload）, thank you.
[SW_SS.sciDOSpost.txt](https://github.com/epri-dev/SCICHEM/files/10979255/SW_SS.sciDOSpost.txt)
[flag.2010.table.6.annual.csv](https://github.com/epri-dev/SCICHEM/files/10979259/flag.2010.table.6.annual.csv)
<img width="643" alt="35fd0f686c457f5f11db06ca1463a18" src="https://user-images.githubusercontent.com/127366298/225300762-c0f6b6e6-153e-40fa-bcf5-22896aa02512.png">

**Comment by DougHenn** [comment]
I'm pretty sure you're reading the NatCond file (sciData\Flag2010flag.2010.table.6.annual.csv). There would have been an error if the file wasn't found.

I just noticed that the file I previously attached was the wrong file.  It was supposed to be the input file with receptor names changed to upper case letters.  Try this one:
[SW_SS.sciDOSpost_UC.inp.txt](https://github.com/epri-dev/SCICHEM/files/10984631/SW_SS.sciDOSpost_UC.inp.txt)

**Comment by qingfengnanmeng** [comment]
Thank you, the problem has been solved。

**Comment by qingfengnanmeng** [comment]
Hello，I have some questions about SCIDOSPOST. The inp file I set is attached,

1. Can the concentration change of time series in the grid be obtained by setting different FTYPEs? rather than the concentration of continuous time changes at each RECEPTORS 

2. When FTYPE in the INP file is GRD, the error message shows that GRD files can only handle one time period. How can I set up to obtain the concentration changes of the grid's time series?

3.When FTYPE in the INP file is POST format, the output is the concentration change of the time series for each receptor point, and there are 14399 RECEPTORS. How is 14399 calculated?

[SW_SS.sciDOSpost_0410.inp.t
![f7f49b92e82ed8a9d5ebe1cb4467467](https://user-images.githubusercontent.com/127366298/232367415-4141d247-5638-4abe-8523-e191255308be.png)
xt](https://github.com/epri-dev/SCICHEM/files/11245716/SW_SS.sciDOSpost_0410.inp.txt)
[o3.pst.txt](https://github.com/epri-dev/SCICHEM/files/11245791/o3.pst.txt)

**Comment by DougHenn** [comment]
1)	I'm not sure if this answers your question but it is possible to get a gridded time series. However, it is not in a convenient format. You cannot use the ‘GRD’ output option (that only works for a single gridded field as mentioned below) but you can use the POST format with a grid receptor file. This will create a file with a line for each receptor for the 1st time step, 2nd time step etc.
2)	The GRD type output produces a single gridded field of a selected pollutant and selected averaging time period or metric (1st highest, 4th highest etc.). This is the Surfer 6 ascii grid file format ([https://grapherhelp.goldensoftware.com/subsys/ascii_grid_file_format.htm]). You cannot get multiple time steps (time series) of the gridded values. To get a time series, use a RECeptor set with only 1 point and 'TIME=ALL' as mentioned in the sample input file provided with the SCICHEM 3.3 package
3)	The 14399 receptors are calculated from the grid definition:
GRID  coarse  LL      0.036  -110.3   34.65     -105.98  38.90  ! approx 4km resolution

**Comment by qingfengnanmeng** [comment]
Hello，I have some questions about the SCIDOSPOST output of the fourth case, and the INP file is attached，
1.I want to output the average concentration of each pollutant over the entire simulation time (17 * 24=408 hr), Why are the output files empty when I set the TIME to ALL, period to 408hr and Statistic to Averagein the INP file?
2. I want to output the average concentration of each pollutant for the entire simulation time of the grid（coarse）. Shouldn't the output grd file be the same when TIME selects 1st or 2nd？ why are all concentration values in the output GRD file (o3_408hr_2nd.grd) the same（-3.402823E+38） when  TIME selecting 2nd?
Thank you very much ！
[o3_408_average.pst .txt](https://github.com/epri-dev/SCICHEM/files/11287333/o3_408_average.pst.txt)
[SW_SS.sciDOSpost_0420.inp.txt](https://github.com/epri-dev/SCICHEM/files/11287354/SW_SS.sciDOSpost_0420.inp.txt)

[o3_408hr_2nd.grd.txt](https://github.com/epri-dev/SCICHEM/files/11287378/o3_408hr_2nd.grd.txt)
[o3_408hr.grd.txt](https://github.com/epri-dev/SCICHEM/files/11287384/o3_408hr.grd.txt)
[no2_408_average.pst.txt](https://github.com/epri-dev/SCICHEM/files/11287417/no2_408_average.pst.txt)

**Comment by pkaramchandani** [comment]
For 1) can you try
con   o3   ug/m3  sam     AllRec  1st  408 hr   Average    PLOT o3_408_average.plt
(i.e., replace "All" with "1st" and try a plot file instead of a post file)

For 2) they appear to be the same but both are garbage values. It's not quite clear why, but please note that the GRD option has not been well tested and we don't use it. We have been working with an option for netCDF outputs but that is incomplete after the sciDOSpost developer departed from our team (the same reason why the GRD option has not been well tested). I would suggest using other options for creating a gridded field (e.g., the option above for a 408-hour average concentration at each grid cell) and writing a script to take the values in the plot file to a format suitable for using in a grid plotting program. We have been successful in doing that for another client, but cannot share the script with you for client confidential reasons.

**Comment by pkaramchandani** [comment]
Hello. If you want to use speciated VOC emissions and their chemistry, the provided full chemistry imc file in the SCICHEM package will address your needs. You need to split up your VOC emissions into the CB6 chemistry mechanism species used in SCICHEM.

If you want to use a generic (or total) VOC, you can specify the emissions for that VOC, but you cannot make use of the full chemistry imc file nor can you do chemistry without providing a relevant chemistry scheme in your custom imc file. So it would have to be an inert simulation if you do not have such a chemistry mechanism. The imc file for the inert simulation would be similar to that provided for the SO2 case in the SCICHEM package.

Hope that helps

**Comment by qingfengnanmeng** [comment]
Hello! When using the CTM2SCICHEM tool to generate background concentration files, all the required files(3D concentration files from CMAQ, GRIDDESC file,etc.) were placed in the specified path. After running the script, daily_prof step has results, but there is no final result. Is this because there is a problem with the shp file of SCICHEM Domain I specified? An error message was displayed as follows，the results of running the script, shp file, and reg_list.txt are all in the attachment，Thank you!

***ERROR ABORT in submarine M3PROMPT

END-OF-FILE encoded
[cz2.log](https://github.com/epri-
[shp.zip](https://github.com/epri-dev/SCICHEM/files/12115363/shp.zip)
dev/SCICHEM/files/12115360/cz2.log)
[reg_list.txt](https://github.com/epri-dev/SCICHEM/files/12115365/reg_list.txt)

**Comment by qingfengnanmeng** [comment]
> Hi
> 
> Are you able to run the processor with the provided shape files for the US states? Can you please test that first to see if it's an issue with your working environment? The CTM2SCICHEM package includes all the files you need for this test.

Hello
It seems that there is no 3D concentration files from CMAQ or CAMx in the CTM2SCICHEM package for the United States. Could you provide a concentration file only for testing purposes? Thank you!

**Comment by qingfengnanmeng** [comment]
Hello, I have a couple of questions for you. 
1. Is there a detailed description of the copyright of the scichem model, and if so, can you tell me how to download or search the file?
2. how many kilometers is the best simulation distance for scichem? What is the maximum distance of the simulation?
3. Is scichem still reliable when simulating multiple sources?
Looking forward to hearing from you. Thank you very much!
